### ISSUE TITLE
Self-hosted HackMD

### ISSUE THREAD

**Issue by rufuspollock** [datopian/pm-#14]
We really like hackmd and intend to use it more and more (even replace gdocs entirely).

We want to be able to limit some parts to team members only.

We want to ensure we have a backup of our docs (at the moment there is no API or way to bulk export your data).

## Tasks

* [ ] Investigate getting these features added to hackmd
* [ ] Investigate self-hosting
* [ ] Decide on any next steps

**Comment by deletosh** [comment]
+1

**Comment by pwalsh** [comment]
Closing as WONTFIX
