### ISSUE TITLE
Research nextjs

### ISSUE THREAD

**Issue by rufuspollock** [datopian/pm-#32]
As Rufus I want to know more about nextjs so that I know what it is and whether it is useful to us in future projects e.g.

* datahub
* static websites
* ...

## Acceptance criteria

* [ ] Intro here with key links
* [ ] Review / opinion here with views on whether we can use this and where (and what strengths / weaknesses are)

## Tasks

* [x] At least one person done the tutorial
* [ ] Try it out for something small (e.g. a tutorial for the datahub)
* [x] Write up intro
* [ ] Write up a review

### Introduction

NextJS is a framework that helps easily and quickly create single-page JavaScript applications. Key points to consider:

* we create pages (and components) in a React way. Pages in `/pages` directory that can reuse components from `/components` directory.
* client-side routing
* it creates bundles for each page using only necessary code (depending what you import)
* we can use it together with ExpresJS

### Benefits

* Client-side routing
  * speed of page loading - great UX
* Caching
  * extremely useful, especially when navigating back and forward (e.g., publisher page <=> showcase page)
* React way
  * component-based approach

### Drawbacks

* initial loading time (due to bundle size)
* requires knowledge of React

Notes about CSS:

> there are a bunch of practical issues to consider with traditional CSS-file-based styling (especially with SSR), so we suggest avoiding this method when styling for Next.js.
Instead we recommend CSS in JS, which you can use to style individual components rather than importing CSS files.

See example here - https://github.com/zeit/next.js/#css

**Comment by anuveyatsu** [comment]
Here is what we've done so far https://hackmd.io/GYJgxgnARgzADBAtAdjAFgKyLTDdHRgBsiwRAHBcBjMgKZR1A===

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. No longer relevant now and well out of date.
